[package]
name = "dungeons-endpoint"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
moka = "0.12.10"
regex = "1.11.1"
reqwest = "0.12.18"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
